spring:
  datasource:
    url: jdbc:mysql://localhost:3306/querydsl
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000

  data:
    web:
      pageable:
        default-page-size: 10
        #one-indexed-parameters: true
        max-page-size: 2000


# p6spy log
logging:
  level:
    p6spy: info
decorator:
  datasource:
    p6spy:
      enable-logging: true